import { MigrationInterface, QueryRunner } from "typeorm";

export class seeds1639059449457 implements MigrationInterface {

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("INSERT INTO `shop`.`roles` (`name`, `description`) VALUES ('USER', 'Користувач')");
        await queryRunner.query("INSERT INTO `shop`.`roles` (`name`, `description`) VALUES ('ADMIN', 'Адміністратор')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Телефони та аксесуари','Телефоны и аксесуары','smartphones-mobiles-accessories','1.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Ноутбуки, компьютери та мфу','Ноутбуки, компьютеры та мфу','notes','2.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('ТВ та електроніка','ТВ и электроника','tv','3.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Аудіо техніка','Аудио техника','audio','4.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Побутова техніка','Бытовая техника','appliances','5.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Сантехніка','Сантехника','plumbing','6.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Автотовари','Автотовары','auto','7.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Велотовари','Велотовары','bicycles','8.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Канцтовари','Канцтовары','stationery','9.svg')");
        await queryRunner.query("INSERT INTO `shop`.`categories` (`name`, `name_ru`, `ref`, `pic`) VALUES ('Сад і город','Сад и огород','garden','10.svg')");
        await queryRunner.query("INSERT INTO `shop`.`groups` (`name`, `name_ru`, `ref`, `pic`, `categoryId`) VALUES ('Смартфони','Смартфоны','smartphones','1.jpg',1)");
        await queryRunner.query("INSERT INTO `shop`.`groups` (`name`, `name_ru`, `ref`, `pic`, `categoryId`) VALUES ('Мобільні телефони','Мобильные телефоны','mobiles','2.jpg',1)");
        await queryRunner.query("INSERT INTO `shop`.`groups` (`name`, `name_ru`, `ref`, `pic`, `categoryId`) VALUES ('Офісні телефони','Офисные телефоны','phones','3.jpg',1)");
        await queryRunner.query("INSERT INTO `shop`.`props` (`name`, `name_ru`) VALUES ('Бренд','Бренд')");
        await queryRunner.query("INSERT INTO `shop`.`props` (`name`, `name_ru`) VALUES ('Об\"єм вбудованої пам\"яті','Объем встроенной памяти')");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('brand-apple','Apple',1)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('brand-samsung','Samsung',1)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('brand-xiaomi','Xiaomi',1)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('brand-nokia','Nokia',1)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('brand-sigma','Sigma',1)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('ram-val_4gb','4 Гб',2)");
        await queryRunner.query("INSERT INTO `shop`.`propdetails` (`id`, `name`, `propId`) VALUES ('ram-val_6gb','6 Гб',2)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (1,'Samsung Galaxy A52 A525F 4/128GB Black (SM-A525FZKDSEK)',2,120000,0,'1.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (2,'Apple iPhone 12 64GB Purple',3,150055,229900,'2.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (3,'Apple iPhone 11 64Gb Black (MHDA3) Slim Box',3,289900,0,'3.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (4,'Samsung Galaxy A12 2021 A125F 4/64GB Blue',1,449900,0,'4.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (5,'Samsung Galaxy A12 2021 A125F 4/64GB Blue-2',5,479900,549900,'5.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (6,'Xiaomi Redmi Note 9 4/128Gb (Forest Green)',3,849900,0,'6.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (7,'Samsung Galaxy M12 2021 M127F 4/64GB Green',10,399900,0,'7.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (8,'Xiaomi Redmi Note 8 2021 4/64GB (White)',7,899900,0,'8.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (9,'Xiaomi Redmi 9T 4/64GB (Carbon Gray)',4,529900,0,'9.webp',1)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (10,'Sigma Comfort 50 Optima (Black)',15,99900,129900,'10.webp',2)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (11,'Sigma X-style 18 Track (Black/Red)',3,349900,389900,'11.webp',2)");
        await queryRunner.query("INSERT INTO `shop`.`products` (`code`, `name`, `amount`, `price`, `priceold`, `pic`, `groupId`) VALUES (12,'Nokia 105 Single Sim 2019 Black NOCHGR',2,199900,0,'12.webp',2)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Samsung',1,'brand-samsung',1)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',1)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Apple',1,'brand-apple',2)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',2)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Apple',1,'brand-apple',3)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',3)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Samsung',1,'brand-samsung',4)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('6 Гб',2,'ram-val_6gb',4)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Samsung',1,'brand-samsung',5)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('6 Гб',2,'ram-val_6gb',5)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Xiaomi',1,'brand-xiaomi',6)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',6)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Samsung',1,'brand-samsung',7)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',7)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Xiaomi',1,'brand-xiaomi',8)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',8)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Xiaomi',1,'brand-xiaomi',9)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('4 Гб',2,'ram-val_4gb',9)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Sigma',1,'brand-sigma',10)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Sigma',1,'brand-sigma',11)");
        await queryRunner.query("INSERT INTO `shop`.`productinfo` (`value`, `propId`, `propdetailId`, `productId`) VALUES ('Nokia',1,'brand-nokia',12)");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("DELETE FROM `shop`.`roles` WHERE (`name`='USER')");
        await queryRunner.query("DELETE FROM `shop`.`roles` WHERE (`name`='ADMIN')");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-samsung' AND `productId`=1)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=1)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='barand-apple' AND `productId`=2)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=2)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='barand-apple' AND `productId`=3)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=3)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-samsung' AND `productId`=4)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_6gb' AND `productId`=4)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-samsung' AND `productId`=5)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_6gb' AND `productId`=5)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-xiaomi' AND `productId`=6)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=6)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-samsung' AND `productId`=7)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=7)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-xiaomi' AND `productId`=8)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=8)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-xiaomi' AND `productId`=9)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='ram-val_4gb' AND `productId`=9)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='barand-sigma' AND `productId`=10)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='barand-sigma' AND `productId`=11)");
        await queryRunner.query("DELETE FROM `shop`.`productinfo` WHERE (`propdetailId`='brand-nokia' AND `productId`=12)");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Samsung Galaxy A52 A525F 4/128GB Black (SM-A525FZKDSEK)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Apple iPhone 12 64GB Purple')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Apple iPhone 11 64Gb Black (MHDA3) Slim Box')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Samsung Galaxy A12 2021 A125F 4/64GB Blue')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Samsung Galaxy A12 2021 A125F 4/64GB Blue-2')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Xiaomi Redmi Note 9 4/128Gb (Forest Green)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Samsung Galaxy M12 2021 M127F 4/64GB Green')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Xiaomi Redmi Note 8 2021 4/64GB (White)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Xiaomi Redmi 9T 4/64GB (Carbon Gray)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Sigma Comfort 50 Optima (Black)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Sigma X-style 18 Track (Black/Red)')");
        await queryRunner.query("DELETE FROM `shop`.`products` WHERE (`name`='Nokia 105 Single Sim 2019 Black NOCHGR')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='barand-apple')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='brand-samsung')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='brand-xiaomi')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='brand-nokia')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='barand-sigma')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='ram-val_4gb')");
        await queryRunner.query("DELETE FROM `shop`.`propdetails` WHERE (`id`='ram-val_6gb')");
        await queryRunner.query("DELETE FROM `shop`.`props` WHERE (`name`='Бренд')");
        await queryRunner.query("DELETE FROM `shop`.`props` WHERE (`name`='Об\"єм вбудованої пам\"яті')");
        await queryRunner.query("DELETE FROM `shop`.`groups` WHERE (`name`='Смартфони')");
        await queryRunner.query("DELETE FROM `shop`.`groups` WHERE (`name`='Мобільні телефони')");
        await queryRunner.query("DELETE FROM `shop`.`groups` WHERE (`name`='Офісні телефони')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Телефони та аксесуари')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Ноутбуки, компьютери та мфу')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='ТВ та електроніка')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Аудіо техніка')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Побутова техніка')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Сантехніка')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Автотовари')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Велотовари')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Канцтовари')");
        await queryRunner.query("DELETE FROM `shop`.`categories` WHERE (`name`='Сад і город')");
    }

}
